### ISSUE TITLE
Solve Java Questions.

### ISSUE THREAD

**Issue by srsandy** [srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore#34]
## Check the repository
You can find the book [*here*](https://github.com/srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore/blob/master/data_structures_and_algorithms_in_javatqw_darksiderg.pdf)

Go to any unsolved chapter solve it's **Programming Projects**.

Keep .java file in the correct folder and update the ReadMe.md accordingly.

Add a PR  😄 and be a  contributor to this repository.

#### Avoid
Collection Classes (Implement everything by your own)

**Comment by arpitjain22june** [comment]
@srsandy  i can't find the book error 404

**Comment by srsandy** [comment]
@arpitjain22june email me sandeepranjan2007@yahoo.co.in
