### ISSUE TITLE
Add competitive coding problems and solutions in JAVA

### ISSUE THREAD

**Issue by srsandy** [srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore#40]
Add a PR with any competitive coding problem
In
- [/Practice Problems/](https://github.com/srsandy/Data-Structures-and-Algorithms-in-Java-2nd-Edition-by-Robert-Lafore/tree/master/Practice%20Problems/) add competitive coding problems and solutions in the respective topic folder

Check other folders in `Arrays` how it is done in rest of file 

E.g
- Add a folder in `Arrays` folder with the *Name of Problem Title*.
- Inside that folder add the solution `ProblemTitle.java` and a `README.md` 
- `README.md` must contain a detail description of the problem.

**Comment by aansari4599** [comment]
I want to add some problems and their solutions that i solved

**Comment by srsandy** [comment]
@aansari4599 sure do it
Follow the structure 
Every problem a different PR

**Comment by aansari4599** [comment]
i have submitted one problem ..It is showing "able to merge" message.
please review it.

**Comment by aansari4599** [comment]
i have added a new problem .please review it. #58

**Comment by pallavijadhav31** [comment]
Hey! i want to add solutions that i solved may i

**Comment by srsandy** [comment]
@pallavijadhav31 go ahead (y)

**Comment by pallavijadhav31** [comment]
@srsandy need your help. As I'm a beginner want to ask i have to make a new branch for PR ??

**Comment by srsandy** [comment]
@pallavijadhav31 you fork and then do the commits. The when you add pr. A new branch will automatically be created as master is protected.
